// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7tt55IgPzwfkh6DSr-9kY44cDS3TeA7o',
    appId: '1:338799022018:web:e65e5f6544725cde42d05b',
    messagingSenderId: '338799022018',
    projectId: 'wallpaper-hub-b1381',
    authDomain: 'wallpaper-hub-b1381.firebaseapp.com',
    storageBucket: 'wallpaper-hub-b1381.appspot.com',
    measurementId: 'G-798858HHYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiWjJLUiym2-WCSp6jIcyQf1m8WgQVV-A',
    appId: '1:338799022018:android:a06b1eddda1efec342d05b',
    messagingSenderId: '338799022018',
    projectId: 'wallpaper-hub-b1381',
    storageBucket: 'wallpaper-hub-b1381.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOMLRIPekB0sIEiCXrUBT4yHou7LmNvRs',
    appId: '1:338799022018:ios:693f8417017983ad42d05b',
    messagingSenderId: '338799022018',
    projectId: 'wallpaper-hub-b1381',
    storageBucket: 'wallpaper-hub-b1381.appspot.com',
    androidClientId: '338799022018-mh16dfbhjadgfq52luf0nnorin7pjdrc.apps.googleusercontent.com',
    iosClientId: '338799022018-41bbpa5g823ln8degidvkrkg84jmvovh.apps.googleusercontent.com',
    iosBundleId: 'm',
  );
}
